name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *"   # Runs once a day at midnight UTC
  workflow_dispatch:       # Allows manual run

jobs:
  update-readme:
    name: Update README with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
